[package]
name = "crystal-core"
version = "0.1.0"
authors = ["Victor Quiroz <victorhqc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
env_logger = "0.6.0"
futures = "0.1"
gotham = "0.4"
gotham_derive = "0.4"
gotham_middleware_diesel = "0.1.0"
http = "0.1"
hyper = "0.12"
league-client-connector = "0.1.0"
log = "0.4"
notify = "4.0"
tokio = "0.1.17"
tokio-threadpool = "0.1.12"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[target.'cfg(unix)'.dependencies]
openssl-probe = "0.1.2"
openssl = "*"