[package]
name = "league-client"
version = "1.0.0"
authors = ["OpenAPI Generator team and contributors"]

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "1.5"
serde_yaml = "0.7"
strum = "0.19"
strum_macros = "0.19"
base64 = "~0.7.0"
